platform :ios, '8.0'
pod 'Parse'
pod 'SSUIViewMiniMe'
pod 'MinimalTabBar'
pod 'FlatUIKit'
pod 'VBFPopFlatButton'
pod 'UIView+FDCollapsibleConstraints'
pod 'ParseFacebookUtils'
pod 'FBSDKCoreKit', '~> 4.2.0'
pod 'FBSDKLoginKit', '~> 4.1.0'
pod 'FBSDKShareKit', '~> 4.1.0'
pod 'SVProgressHUD'
pod 'MZFormSheetController'
pod 'JSQMessagesViewController'
pod 'SVPullToRefresh'
pod 'DVITutorialView'
pod 'JFMinimalNotifications'
